### ISSUE TITLE
Display the Sql lite database on the Patients.fxml / PatientsController

### ISSUE THREAD

**Issue by rc9207** [rc9207/Animal-Shelter-Project#6]
Pull data from data base and display it on the Patients Scene.

**Comment by rc9207** [comment]
Add method in the Database.java to load animal into HBox on Patient Controller. For now data should be sorted by Animal ID

**Comment by JoshuaColicchio** [comment]
![](https://media.giphy.com/media/WoojKu8BFDYbN5Fk9S/giphy.gif)

It isn't super pretty yet, but the functionality is there.
